### ISSUE TITLE
Composer toolbar: dollar button appears first

### ISSUE THREAD

**Issue by exomarty** [benjaminabel/nodebb-plugin-katex#5]
Can you please fix plugin so katex icon doesnt append first?

![screenshot_2](https://cloud.githubusercontent.com/assets/10746278/19521835/7b7d285a-9615-11e6-881e-b14611601440.png)

**Comment by ghost** [comment]
Hi @exomarty, thanks for your interest. Are you sure you ordered plugins to load the plugin after `nodebb-plugin-markdown` as indicated in README.

**Comment by exomarty** [comment]
i do

**Comment by ghost** [comment]
You're right this is not the normal way it was displayed. I need to work on this. Thanks.

**Comment by ghost** [comment]
Fixed on 0.2.1. Changed the priority of the `registerFormatting` hook in this [commit](https://github.com/benjaminabel/nodebb-plugin-katex/commit/0a7337f91c4a267be9e845f41f3f11376001b75c)

**Comment by exomarty** [comment]
Thanl you :)
